services:
  casa:
    image: dockurr/casa
    container_name: casa
    ports:
      - 8080:8080
    volumes:
      - "/home/example:/DATA"
      - "/var/run/docker.sock:/var/run/docker.sock"
    stop_grace_period: 1m
